module.exports = {
  ERROR_ICORRECT_USER_ID: 'Передан некорректный идентификатор пользователя',
  ERROR_USER_NOT_FOUND: 'Пользователь с указанным _id не найден',
  ERROR_NEW_USER_PARAMS: 'Переданы некорректные данные при создании пользователя',
  ERROR_EDIT_USER_PARAMS: 'Переданы некорректные данные при редактировании профиля',
  ERROR_EDIT_AVATAR_PARAMS: 'Переданы некорректные данные при редактировании аватара',
  ERROR_CARD_NOT_FOUND: 'Карточка с указанным _id не найдена',
  ERROR_NEW_CARD_PARAMS: 'Переданы некорректные данные при создании карточки',
  ERROR_CARD_LIKES_PARAMS: 'Переданы некорректные данные для постановки/снятии лайка.',
  ERROR_PARAMS: 'Переданы некорректные параметры',
  ERROR_EMAIL_ALREDY_EXISTS: 'Указанный email уже занят',
  ERROR_AUTHORIZATION_REQUIRED: 'Необходима авторизация',
  ERROR_AUTHORIZATION: 'Ошибка авторизации',
  ERROR_LOGIN: 'Ошибка входа',
  ERROR_LOGIN_PASSWORD: 'Неправильная почта или пароль',
  ERROR_BAD_REQUEST: 'Неправильный запрос',
  ERROR_DELETE_CARD_NOT_OWNERED: 'Запрещено удалять карточку, владельцем которой вы не являетесь',
  ERROR_SERVER: 'Ошибка сервера',
};
